version = 1

test_patterns = [
  "**/*_test.go"
]

exclude_patterns = [
  "doc/**",
  "**/*.pb.go"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/relab/gorums"

[[analyzers]]
name = "shell"
enabled = true
